#01-create-app-user.sh
#!bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$APP_USER" WITH PASSWORD '$APP_PASSWORD';
  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$APP_USER";
  GRANT USAGE, CREATE ON SCHEMA public TO "$APP_USER";
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$APP_USER"
EOSQL
