TYPE_MAP = {
    "agency_id":"TEXT",
    "agency_name": "TEXT",
    "agency_url": "TEXT",
    "agency_timezone": "TEXT",
    "agency_lang": "VARCHAR(2)",
    "agency_phone": "TEXT",
    "agency_fare_url": "TEXT",
    "service_id": "TEXT",
    "monday": "INTEGER",
    "tuesday": "INTEGER",
    "wednesday": "INTEGER",
    "thursday": "INTEGER",
    "friday": "INTEGER",
    "saturday": "INTEGER",
    "sunday": "INTEGER",
    "start_date": "DATE",
    "end_date": "DATE",
    "exception_type": "INTEGER",
    "id": "INTEGER",
    "name": "TEXT",
    "route_id": "TEXT",
    "route_short_time": "INTEGER",
    "route_long_name": "TEXT",
    "route_type": "INTEGER",
    "route_url": "TEXT",
    "route_color": "TEXT",
    "route_text_color": "TEXT",
    "shape_id": "TEXT",
    "shape_pt_lat": "FLOAT",
    "shape_pt_lon": "FLOAT",
    "shape_pt_sequence": "INTEGER",
    "stop_id": "TEXT",
    "stop_code": "TEXT",
    "stop_name": "TEXT",
    "stop_lat": "FLOAT",
    "stop_lon": "FLOAT",
    "zone_id": "TEXT",
    "wheelchair_boarding": "TEXT",
    "wheelchair_accessible": "TEXT",
    "municipality_id": "INTEGER",
    "from_stop_id": "TEXT",
    "to_stop_id": "TEXT",
    "transfer_type": "INTEGER",
    "min_transfer_time": "TEXT",
    "from_route_id": "TEXT",
    "from_trip_id": "TEXT",
    "to_route_id": "TEXT",
    "to_trip_id": "TEXT",
    "trip_id": "TEXT",
    "trip_headsign": "TEXT",
    "direction_id": "TEXT",
    "block_id": "TEXT",
    "shape_id": "TEXT",
    "bikes_allowed": "INTEGER",
    "date": "DATE",
    "route_short_name": "TEXT",
    "arrival_time": "INTERVAL",
    "departure_time": "INTERVAL",
    "stop_sequence": "INTEGER",
    "stop_headsign": "TEXT",
    "pickup_type": "INTEGER",
    "drop_off_type": "INTEGER",
    "timepoint": "INTEGER"

}

PRIMARY_KEYS = {
   "agency" : "agency_id",
    "calendar": "service_id",
    "calendar_dates": "service_id, date",
    "municipalities": "id",
    "routes": "route_id",
    "shapes": "shape_id, shape_pt_sequence",
    "stops": "stop_id",
    "trips": "trip_id"
}

FOREIGN_KEYS = {
    "routes" : [{"column": "agency_id", "parent_table":  "agency", "parent_column": "agency_id"}],
    "stops": [{"column": "municipality_id", "parent_table": "municipalities", "parent_column": "id"}],
    "calendar_dates": [{"column": "service_id", "parent_table": "calendar", "parent_column": "service_id"}],
    "trips": [{"column": "route_id", "parent_table": "routes", "parent_column": "route_id"},
              {"column": "service_id", "parent_table": "calendar_dates", "parent_column": "service_id"},
              {"column": "shape_id", "parent_table": "shapes_metadata", "parent_column": "shape_id"}],
    "transfers": [{"column": "from_stop_id", "parent_table": "stops", "parent_column": "stop_id"},
                  {"column": "to_stop_id", "parent_table": "stops", "parent_column": "stop_id"},
                  {"column": "from_route_id", "parent_table": "routes", "parent_column": "route_id"},
                  {"column": "to_route_id", "parent_table": "routes", "parent_column": "route_id"},
                  {"column": "from_trip_id", "parent_table": "trips", "parent_column": "trip_id"},
                  {"column": "from_trip_id", "parent_table": "trips", "parent_column": "trip_id"}]
}

TABLES_TO_SKIP = ["fare_attributes", "fare_rules"]
